TOP_N = 10
PINNED = ["BTC", "ETH", "SOL", "HYPE"]
STABLECOINS = {
    "USDC", "USDT", "USDE", "USDT0", "DAI", "FDUSD", "TUSD",
    "USDD", "PYUSD", "USDB", "USDX", "FRAX", "LUSD", "GUSD",
    "USDHL", "USR", "USD", "USDC0"
}

MAX_POSITIONS = 3
LEVERAGE = 2
INTERVAL_MINUTES = 60
SLIPPAGE = 0.05
SETTLE_SECONDS = 3
MAX_ORACLE_GAP_PCT = 3.0
MAKER_WAIT_SECONDS = 30

VOL_TARGET_PCT = 0.02
MAX_NOTIONAL_USD = 200
MIN_NOTIONAL_USD = 20

STOP_ATR_MULT = 3.0
ATR_PERIOD = 14

SUPERTREND_PERIOD = 14
SUPERTREND_MULT = 3.0

ADX_PERIOD = 14
ADX_THRESHOLD = 25

TRADE_LOG = "data/trades.json"
EQUITY_LOG = "data/equity_curve.json"
